/*
 * generated by Xtext
 */
package com.vmware.in.testframework;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestFrameworkRuntimeModule extends com.vmware.in.testframework.AbstractTestFrameworkRuntimeModule {

}
