/*
* generated by Xtext
*/
package com.vmware.in.testframework.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.vmware.in.testframework.services.TestFrameworkGrammarAccess;

public class TestFrameworkParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TestFrameworkGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.vmware.in.testframework.parser.antlr.internal.InternalTestFrameworkParser createParser(XtextTokenStream stream) {
		return new com.vmware.in.testframework.parser.antlr.internal.InternalTestFrameworkParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TestFrameworkGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TestFrameworkGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
