/*
* generated by Xtext
*/
package com.vmware.in.testframework.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TestFrameworkAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/vmware/in/testframework/parser/antlr/internal/InternalTestFramework.tokens");
	}
}
