/*
 * generated by Xtext
 */
package com.vmware.in.testframework.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.vmware.in.testframework.ui.internal.TestFrameworkActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TestFrameworkExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TestFrameworkActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TestFrameworkActivator.getInstance().getInjector(TestFrameworkActivator.COM_VMWARE_IN_TESTFRAMEWORK_TESTFRAMEWORK);
	}
	
}
