/**
 * generated by Xtext
 */
package com.vmware.in.testframework.validation;

import com.vmware.in.testframework.validation.AbstractTestFrameworkValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TestFrameworkValidator extends AbstractTestFrameworkValidator {
}
