/*
 * generated by Xtext
 */
package com.vmware.in.testframework.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTestFrameworkValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.vmware.in.testframework.testFramework.TestFrameworkPackage.eINSTANCE);
		return result;
	}
}
