/*
* generated by Xtext
*/
package com.vmware.in.testframework;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TestFrameworkUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.vmware.in.testframework.ui.internal.TestFrameworkActivator.getInstance().getInjector("com.vmware.in.testframework.TestFramework");
	}
	
}
