/*
 * generated by Xtext
 */
package com.vmware.in.testframework.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestFrameworkUiModule extends com.vmware.in.testframework.ui.AbstractTestFrameworkUiModule {
	public TestFrameworkUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
